export const BROADCAST_KEYS = {
    SCROLL_END: 'SCROLL_END', 
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR', 
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    ON_PLAY: 'ON_PLAY',
    ON_GETTING_CURRENTTRACK: 'ON_GETTING_CURRENTTRACK'
}